// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3khM9wPYGoz7yzdqfA3aSDh0mLfa28A4',
    appId: '1:1018911373199:web:5bd880837e7220323bfdfa',
    messagingSenderId: '1018911373199',
    projectId: 'phoneauth-6c46c',
    authDomain: 'phoneauth-6c46c.firebaseapp.com',
    storageBucket: 'phoneauth-6c46c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbea0v1naZDh8CGe1TQLCPOCm5MSuReos',
    appId: '1:1018911373199:android:6400a3c9fd26508b3bfdfa',
    messagingSenderId: '1018911373199',
    projectId: 'phoneauth-6c46c',
    storageBucket: 'phoneauth-6c46c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIIuErGzT-e2ee5fOmkvEsCRTX-NGUzBs',
    appId: '1:1018911373199:ios:dc38b5aac6e6bd013bfdfa',
    messagingSenderId: '1018911373199',
    projectId: 'phoneauth-6c46c',
    storageBucket: 'phoneauth-6c46c.appspot.com',
    androidClientId: '1018911373199-j3vspevte3jnkh2k37f0hofsk2aictgo.apps.googleusercontent.com',
    iosClientId: '1018911373199-vr0b0i36b4lrmmnmvtumfn1k98u9tib1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIIuErGzT-e2ee5fOmkvEsCRTX-NGUzBs',
    appId: '1:1018911373199:ios:15e9ebdeedf51b8b3bfdfa',
    messagingSenderId: '1018911373199',
    projectId: 'phoneauth-6c46c',
    storageBucket: 'phoneauth-6c46c.appspot.com',
    androidClientId: '1018911373199-j3vspevte3jnkh2k37f0hofsk2aictgo.apps.googleusercontent.com',
    iosClientId: '1018911373199-cm08o63go8natfbld9q0sicvq4god269.apps.googleusercontent.com',
    iosBundleId: 'com.example.authSocial.RunnerTests',
  );
}
